---
# tasks file for openvpn

- name: Import assert.yml
  ansible.builtin.import_tasks:
    file: assert.yml
  run_once: true
  delegate_to: localhost

- name: Install openvpn packages
  ansible.builtin.package:
    name: "{{ openvpn_packages }}"
    state: present
  when:
    - openvpn_role != "gen"

- name: Setup openvpn server or client
  ansible.builtin.include_tasks:
    file: "{{ openvpn_role }}.yml"
  when:
    - openvpn_role != "gen"

- name: Start and enable openvpn
  ansible.builtin.service:
    name: "{{ openvpn_service }}"
    state: started
    enabled: true
  when:
    - openvpn_role == "server"
- name: gen client
  block:
    - name: create local client folder
      delegate_to: localhost
      file:
        path: volume/openvpn/client
        state: directory
    - name: confirm common name
      pause:
        prompt: "common name"
      register: cn_input
      when: cn is not defined
    - set_fact:
        cn: "{{ cn_input.user_input }}"
      when: cn_input.user_input is defined
    - name: gen openvpn client pki
      ansible.builtin.command:
        cmd: "{{ openvpn_easyrsa_path }}/easyrsa build-client-full {{ cn }} nopass"
        chdir: /etc/openvpn/server/{{ service_name }}/easy-rsa
        creates: /etc/openvpn/server/{{ service_name }}/easy-rsa/pki/issued/{{ cn }}.crt
      environment:
        EASYRSA_BATCH: "yes"
    - name: create client ovpn file
      ansible.builtin.template:
        src: client.ovpn.j2
        dest: /tmp/{{ cn }}.ovpn
        mode: "0644"
    - name: fetch client ovpn file to local
      ansible.builtin.fetch:
        src: /tmp/{{ cn }}.ovpn
        dest: volume/openvpn/client/{{ cn }}.ovpn
        flat: true
      notify:
        - download ovpn file
  when:
    - openvpn_role == "gen"
