---
# handlers file for openvpn

- name: Restart openvpn
  ansible.builtin.service:
    name: "{{ openvpn_service }}"
    state: restarted

- name: download ovpn file
  ansible.builtin.debug:
    msg: "Client configuration file {{ cn }}.ovpn has been generated and saved to volume/openvpn/client/"
